name: StrikeMMO
main: StrikeMMO\Base
api: 2.0.0
version: 1.0
author: DayKoala
commands:
    mcstats:
        description: MMOStats
    mctop:
        description: MMOTop
    booster:
        description: MMOBooster
