name: StrikeMMO
main: StrikeMMO\Base
api: [2.0.0, 3.0.0, 3.0.0-ALPHA10]
version: 1.0
author: DayKoala
commands:
    mcstats:
        description: MMOStats
    mctop:
        description: MMOTop
    booster:
        description: MMOBooster
